name: Robot Framework Web Tests - Magiclass

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make geckodriver executable
        run: chmod +x ./drivers/geckodriver

      - name: Add geckodriver to PATH
        run: echo "${{ github.workspace }}/drivers" >> $GITHUB_PATH

      - name: Install Firefox
        run: sudo apt-get update && sudo apt-get install -y firefox

      - name: Run Robot Framework Tests
        run: |
          robot --variable BROWSER:firefox --outputdir results tests/

      - name: Upload Robot Results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
