name: Robot Framework Web Tests - Magiclass

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Instala Firefox e GeckoDriver automaticamente
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v2

      - name: Check Firefox version
        run: firefox --version

      - name: Run Robot Framework Tests
        run: |
          robot --outputdir results tests/

      - name: Upload Robot Results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
